GET https://daniel-dervishi-phonebook.herokuapp.com/api/persons

###

GET https://daniel-dervishi-phonebook.herokuapp.com/api/persons/2


###
DELETE https://daniel-dervishi-phonebook.herokuapp.com/759676196.2200814


###
POST https://daniel-dervishi-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Daniel",
    "number": "1"
}